name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install gh-pages
        run: npm install gh-pages --save-dev

      - name: Build
        run: npm run build

      - name: Verify dist folder
        run: |
          ls dist

      - name: Configure Git user
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NeuraAdm/Neura.git
          npm run deploy
